theme: jekyll-theme-profile
title: Jekyll Awesome Nav
description: Folder-based navigation for Jekyll with automatic generation and local subtree overrides.
repository: PrimerPages/jekyll-awesome-nav
permalink: pretty
style: appbar
repo_info: true
user_metadata: false
profile_link: false
nav:
  - name: Overview
    url: /
  - name: Docs Home
    url: /docs/
  - name: Getting Started
    url: /docs/getting-started/
plugins:
  - jekyll-awesome-nav
  - jekyll-seo-tag
  - jekyll-toc
awesome_nav:
  enabled: true
  root: docs
  nav_filename: .nav.yml
toc:
  max_level: 2 # default: 6
markdown: kramdown
defaults:
  - scope:
      path: ""
    values:
      layout: page
  - scope:
      path: "docs"
    values:
      layout: awesome_nav_demo
      toc: true
